// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: dpkms.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GraphNode is a typed node within a KnowledgeObject's intra-object graph.
type GraphNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                             // "<objectID>/<nodeType>/<ordinal>"
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // section | tag | entity_mention | decision | task | summary | code_block
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Order         int32                  `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_dpkms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{0}
}

func (x *GraphNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *GraphNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GraphNode) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GraphNode) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

// GraphEdge is a directed edge between two nodes in the same object graph.
type GraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	EdgeType      string                 `protobuf:"bytes,4,opt,name=edge_type,json=edgeType,proto3" json:"edge_type,omitempty"` // contains | references | resolves_to | derives_from
	Weight        float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_dpkms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{1}
}

func (x *GraphEdge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphEdge) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *GraphEdge) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *GraphEdge) GetEdgeType() string {
	if x != nil {
		return x.EdgeType
	}
	return ""
}

func (x *GraphEdge) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// ObjectGraph holds typed nodes and edges for a single KnowledgeObject.
type ObjectGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectGraph) Reset() {
	*x = ObjectGraph{}
	mi := &file_dpkms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectGraph) ProtoMessage() {}

func (x *ObjectGraph) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectGraph.ProtoReflect.Descriptor instead.
func (*ObjectGraph) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectGraph) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ObjectGraph) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

// Section is a structural section of a knowledge object.
type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Order         int32                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_dpkms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{3}
}

func (x *Section) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Section) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Section) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

// DocumentProjection is the derived human-facing view of a KnowledgeObject.
type DocumentProjection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Sections      []*Section             `protobuf:"bytes,3,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentProjection) Reset() {
	*x = DocumentProjection{}
	mi := &file_dpkms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentProjection) ProtoMessage() {}

func (x *DocumentProjection) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentProjection.ProtoReflect.Descriptor instead.
func (*DocumentProjection) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentProjection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentProjection) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *DocumentProjection) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

// KnowledgeObject is the central proto type for an ingested piece of knowledge.
type KnowledgeObject struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type        string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Source      string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	RawContent  string                 `protobuf:"bytes,4,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	TextContent string                 `protobuf:"bytes,5,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	Pipeline    string                 `protobuf:"bytes,6,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	ProfileId   string                 `protobuf:"bytes,7,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// graph holds canonical node/edge structure; populated when graph_json is stored.
	Graph *ObjectGraph `protobuf:"bytes,10,opt,name=graph,proto3" json:"graph,omitempty"`
	// document_view is the derived document projection; populated on demand.
	DocumentView  *DocumentProjection `protobuf:"bytes,11,opt,name=document_view,json=documentView,proto3" json:"document_view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeObject) Reset() {
	*x = KnowledgeObject{}
	mi := &file_dpkms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeObject) ProtoMessage() {}

func (x *KnowledgeObject) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeObject.ProtoReflect.Descriptor instead.
func (*KnowledgeObject) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{5}
}

func (x *KnowledgeObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeObject) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KnowledgeObject) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *KnowledgeObject) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *KnowledgeObject) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *KnowledgeObject) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *KnowledgeObject) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *KnowledgeObject) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KnowledgeObject) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *KnowledgeObject) GetGraph() *ObjectGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *KnowledgeObject) GetDocumentView() *DocumentProjection {
	if x != nil {
		return x.DocumentView
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Aliases       []string               `protobuf:"bytes,5,rep,name=aliases,proto3" json:"aliases,omitempty"`
	ContentStatus string                 `protobuf:"bytes,6,opt,name=content_status,json=contentStatus,proto3" json:"content_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_dpkms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{6}
}

func (x *Entity) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Entity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Entity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Entity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Entity) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *Entity) GetContentStatus() string {
	if x != nil {
		return x.ContentStatus
	}
	return ""
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Pipeline      string                 `protobuf:"bytes,5,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	ResultId      string                 `protobuf:"bytes,7,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	RetryCount    int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,10,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_dpkms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{7}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Job) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *Job) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Job) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *Job) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Job) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Job) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Job) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// NodeHit is a search result pointing to a matching node within an object.
type NodeHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	NodeRef       string                 `protobuf:"bytes,2,opt,name=node_ref,json=nodeRef,proto3" json:"node_ref,omitempty"` // canonical NodeURI: "ctxt:node/<objectID>/<nodeType>/<ordinal>"
	NodeType      string                 `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Snippet       string                 `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHit) Reset() {
	*x = NodeHit{}
	mi := &file_dpkms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHit) ProtoMessage() {}

func (x *NodeHit) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHit.ProtoReflect.Descriptor instead.
func (*NodeHit) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{8}
}

func (x *NodeHit) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *NodeHit) GetNodeRef() string {
	if x != nil {
		return x.NodeRef
	}
	return ""
}

func (x *NodeHit) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NodeHit) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *NodeHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// NodeAwareFilter constrains node-aware search by node/edge type.
type NodeAwareFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeTypes      []string               `protobuf:"bytes,1,rep,name=node_types,json=nodeTypes,proto3" json:"node_types,omitempty"`                   // restrict to objects containing these node types
	EdgeTypes      []string               `protobuf:"bytes,2,rep,name=edge_types,json=edgeTypes,proto3" json:"edge_types,omitempty"`                   // restrict to objects containing these edge types
	ReturnNodeHits bool                   `protobuf:"varint,3,opt,name=return_node_hits,json=returnNodeHits,proto3" json:"return_node_hits,omitempty"` // when true, results include per-node NodeHit entries
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeAwareFilter) Reset() {
	*x = NodeAwareFilter{}
	mi := &file_dpkms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAwareFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAwareFilter) ProtoMessage() {}

func (x *NodeAwareFilter) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAwareFilter.ProtoReflect.Descriptor instead.
func (*NodeAwareFilter) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{9}
}

func (x *NodeAwareFilter) GetNodeTypes() []string {
	if x != nil {
		return x.NodeTypes
	}
	return nil
}

func (x *NodeAwareFilter) GetEdgeTypes() []string {
	if x != nil {
		return x.EdgeTypes
	}
	return nil
}

func (x *NodeAwareFilter) GetReturnNodeHits() bool {
	if x != nil {
		return x.ReturnNodeHits
	}
	return false
}

// NodeAwareResult wraps a KnowledgeObject with optional node-level hits.
type NodeAwareResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *KnowledgeObject       `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	NodeHits      []*NodeHit             `protobuf:"bytes,2,rep,name=node_hits,json=nodeHits,proto3" json:"node_hits,omitempty"`
	DocumentView  *DocumentProjection    `protobuf:"bytes,3,opt,name=document_view,json=documentView,proto3" json:"document_view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAwareResult) Reset() {
	*x = NodeAwareResult{}
	mi := &file_dpkms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAwareResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAwareResult) ProtoMessage() {}

func (x *NodeAwareResult) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAwareResult.ProtoReflect.Descriptor instead.
func (*NodeAwareResult) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{10}
}

func (x *NodeAwareResult) GetObject() *KnowledgeObject {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *NodeAwareResult) GetNodeHits() []*NodeHit {
	if x != nil {
		return x.NodeHits
	}
	return nil
}

func (x *NodeAwareResult) GetDocumentView() *DocumentProjection {
	if x != nil {
		return x.DocumentView
	}
	return nil
}

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Pipeline      string                 `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	SourceTitle   string                 `protobuf:"bytes,5,opt,name=source_title,json=sourceTitle,proto3" json:"source_title,omitempty"`
	Raw           bool                   `protobuf:"varint,6,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_dpkms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{11}
}

func (x *AnalyzeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AnalyzeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnalyzeRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *AnalyzeRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AnalyzeRequest) GetSourceTitle() string {
	if x != nil {
		return x.SourceTitle
	}
	return ""
}

func (x *AnalyzeRequest) GetRaw() bool {
	if x != nil {
		return x.Raw
	}
	return false
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_dpkms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{12}
}

func (x *AnalyzeResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_dpkms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{13}
}

func (x *GetJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // pending | running | completed | failed
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_dpkms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{14}
}

func (x *ListJobsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_dpkms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{15}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WatchJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchJobRequest) Reset() {
	*x = WatchJobRequest{}
	mi := &file_dpkms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchJobRequest) ProtoMessage() {}

func (x *WatchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchJobRequest.ProtoReflect.Descriptor instead.
func (*WatchJobRequest) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{16}
}

func (x *WatchJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type JobStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ResultId      string                 `protobuf:"bytes,4,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusUpdate) Reset() {
	*x = JobStatusUpdate{}
	mi := &file_dpkms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusUpdate) ProtoMessage() {}

func (x *JobStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusUpdate.ProtoReflect.Descriptor instead.
func (*JobStatusUpdate) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{17}
}

func (x *JobStatusUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatusUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobStatusUpdate) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *JobStatusUpdate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_dpkms_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{18}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*KnowledgeObject     `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_dpkms_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{19}
}

func (x *SearchResponse) GetObjects() []*KnowledgeObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Pipeline      string                 `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	ProfileId     string                 `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_dpkms_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{20}
}

func (x *ListObjectsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListObjectsRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *ListObjectsRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ListObjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListObjectsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*KnowledgeObject     `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_dpkms_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{21}
}

func (x *ListObjectsResponse) GetObjects() []*KnowledgeObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListObjectsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_dpkms_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{22}
}

func (x *GetObjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NodeAwareSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Filter        *NodeAwareFilter       `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAwareSearchRequest) Reset() {
	*x = NodeAwareSearchRequest{}
	mi := &file_dpkms_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAwareSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAwareSearchRequest) ProtoMessage() {}

func (x *NodeAwareSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAwareSearchRequest.ProtoReflect.Descriptor instead.
func (*NodeAwareSearchRequest) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{23}
}

func (x *NodeAwareSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *NodeAwareSearchRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *NodeAwareSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *NodeAwareSearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *NodeAwareSearchRequest) GetFilter() *NodeAwareFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type NodeAwareSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*NodeAwareResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAwareSearchResponse) Reset() {
	*x = NodeAwareSearchResponse{}
	mi := &file_dpkms_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAwareSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAwareSearchResponse) ProtoMessage() {}

func (x *NodeAwareSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAwareSearchResponse.ProtoReflect.Descriptor instead.
func (*NodeAwareSearchResponse) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{24}
}

func (x *NodeAwareSearchResponse) GetResults() []*NodeAwareResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *NodeAwareSearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntitiesRequest) Reset() {
	*x = ListEntitiesRequest{}
	mi := &file_dpkms_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntitiesRequest) ProtoMessage() {}

func (x *ListEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntitiesRequest.ProtoReflect.Descriptor instead.
func (*ListEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{25}
}

func (x *ListEntitiesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListEntitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEntitiesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntitiesResponse) Reset() {
	*x = ListEntitiesResponse{}
	mi := &file_dpkms_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntitiesResponse) ProtoMessage() {}

func (x *ListEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ListEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{26}
}

func (x *ListEntitiesResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ListEntitiesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_dpkms_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{27}
}

func (x *GetEntityRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetEntityBacklinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityBacklinksRequest) Reset() {
	*x = GetEntityBacklinksRequest{}
	mi := &file_dpkms_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityBacklinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityBacklinksRequest) ProtoMessage() {}

func (x *GetEntityBacklinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityBacklinksRequest.ProtoReflect.Descriptor instead.
func (*GetEntityBacklinksRequest) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{28}
}

func (x *GetEntityBacklinksRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetEntityBacklinksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetEntityBacklinksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetEntityBacklinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*KnowledgeObject     `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityBacklinksResponse) Reset() {
	*x = GetEntityBacklinksResponse{}
	mi := &file_dpkms_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityBacklinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityBacklinksResponse) ProtoMessage() {}

func (x *GetEntityBacklinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpkms_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityBacklinksResponse.ProtoReflect.Descriptor instead.
func (*GetEntityBacklinksResponse) Descriptor() ([]byte, []int) {
	return file_dpkms_proto_rawDescGZIP(), []int{29}
}

func (x *GetEntityBacklinksResponse) GetObjects() []*KnowledgeObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *GetEntityBacklinksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_dpkms_proto protoreflect.FileDescriptor

const file_dpkms_proto_rawDesc = "" +
	"\n" +
	"\vdpkms.proto\x12\bdpkms.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n" +
	"\tGraphNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x05R\x05order\"~\n" +
	"\tGraphEdge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x03 \x01(\tR\x04toId\x12\x1b\n" +
	"\tedge_type\x18\x04 \x01(\tR\bedgeType\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\"c\n" +
	"\vObjectGraph\x12)\n" +
	"\x05nodes\x18\x01 \x03(\v2\x13.dpkms.v1.GraphNodeR\x05nodes\x12)\n" +
	"\x05edges\x18\x02 \x03(\v2\x13.dpkms.v1.GraphEdgeR\x05edges\"O\n" +
	"\aSection\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x05R\x05order\"m\n" +
	"\x12DocumentProjection\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12-\n" +
	"\bsections\x18\x03 \x03(\v2\x11.dpkms.v1.SectionR\bsections\"\xb2\x03\n" +
	"\x0fKnowledgeObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1f\n" +
	"\vraw_content\x18\x04 \x01(\tR\n" +
	"rawContent\x12!\n" +
	"\ftext_content\x18\x05 \x01(\tR\vtextContent\x12\x1a\n" +
	"\bpipeline\x18\x06 \x01(\tR\bpipeline\x12\x1d\n" +
	"\n" +
	"profile_id\x18\a \x01(\tR\tprofileId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12+\n" +
	"\x05graph\x18\n" +
	" \x01(\v2\x15.dpkms.v1.ObjectGraphR\x05graph\x12A\n" +
	"\rdocument_view\x18\v \x01(\v2\x1c.dpkms.v1.DocumentProjectionR\fdocumentView\"\xb3\x01\n" +
	"\x06Entity\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x18\n" +
	"\aaliases\x18\x05 \x03(\tR\aaliases\x12%\n" +
	"\x0econtent_status\x18\x06 \x01(\tR\rcontentStatus\"\xf4\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x1a\n" +
	"\bpipeline\x18\x05 \x01(\tR\bpipeline\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1b\n" +
	"\tresult_id\x18\a \x01(\tR\bresultId\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\n" +
	" \x01(\x05R\n" +
	"maxRetries\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x8e\x01\n" +
	"\aNodeHit\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12\x19\n" +
	"\bnode_ref\x18\x02 \x01(\tR\anodeRef\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\tR\bnodeType\x12\x18\n" +
	"\asnippet\x18\x04 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\"y\n" +
	"\x0fNodeAwareFilter\x12\x1d\n" +
	"\n" +
	"node_types\x18\x01 \x03(\tR\tnodeTypes\x12\x1d\n" +
	"\n" +
	"edge_types\x18\x02 \x03(\tR\tedgeTypes\x12(\n" +
	"\x10return_node_hits\x18\x03 \x01(\bR\x0ereturnNodeHits\"\xb7\x01\n" +
	"\x0fNodeAwareResult\x121\n" +
	"\x06object\x18\x01 \x01(\v2\x19.dpkms.v1.KnowledgeObjectR\x06object\x12.\n" +
	"\tnode_hits\x18\x02 \x03(\v2\x11.dpkms.v1.NodeHitR\bnodeHits\x12A\n" +
	"\rdocument_view\x18\x03 \x01(\v2\x1c.dpkms.v1.DocumentProjectionR\fdocumentView\"\xa7\x01\n" +
	"\x0eAnalyzeRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bpipeline\x18\x03 \x01(\tR\bpipeline\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12!\n" +
	"\fsource_title\x18\x05 \x01(\tR\vsourceTitle\x12\x10\n" +
	"\x03raw\x18\x06 \x01(\bR\x03raw\"(\n" +
	"\x0fAnalyzeResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x1f\n" +
	"\rGetJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x0fListJobsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"K\n" +
	"\x10ListJobsResponse\x12!\n" +
	"\x04jobs\x18\x01 \x03(\v2\r.dpkms.v1.JobR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"!\n" +
	"\x0fWatchJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xae\x01\n" +
	"\x0fJobStatusUpdate\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1b\n" +
	"\tresult_id\x18\x04 \x01(\tR\bresultId\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"r\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"[\n" +
	"\x0eSearchResponse\x123\n" +
	"\aobjects\x18\x01 \x03(\v2\x19.dpkms.v1.KnowledgeObjectR\aobjects\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x91\x01\n" +
	"\x12ListObjectsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bpipeline\x18\x02 \x01(\tR\bpipeline\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"`\n" +
	"\x13ListObjectsResponse\x123\n" +
	"\aobjects\x18\x01 \x03(\v2\x19.dpkms.v1.KnowledgeObjectR\aobjects\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\"\n" +
	"\x10GetObjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xae\x01\n" +
	"\x16NodeAwareSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x121\n" +
	"\x06filter\x18\x05 \x01(\v2\x19.dpkms.v1.NodeAwareFilterR\x06filter\"d\n" +
	"\x17NodeAwareSearchResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.dpkms.v1.NodeAwareResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"a\n" +
	"\x13ListEntitiesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"Z\n" +
	"\x14ListEntitiesResponse\x12,\n" +
	"\bentities\x18\x01 \x03(\v2\x10.dpkms.v1.EntityR\bentities\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"&\n" +
	"\x10GetEntityRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"]\n" +
	"\x19GetEntityBacklinksRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"g\n" +
	"\x1aGetEntityBacklinksResponse\x123\n" +
	"\aobjects\x18\x01 \x03(\v2\x19.dpkms.v1.KnowledgeObjectR\aobjects\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2P\n" +
	"\x0eAnalyzeService\x12>\n" +
	"\aAnalyze\x12\x18.dpkms.v1.AnalyzeRequest\x1a\x19.dpkms.v1.AnalyzeResponse2\xc5\x01\n" +
	"\n" +
	"JobService\x120\n" +
	"\x06GetJob\x12\x17.dpkms.v1.GetJobRequest\x1a\r.dpkms.v1.Job\x12A\n" +
	"\bListJobs\x12\x19.dpkms.v1.ListJobsRequest\x1a\x1a.dpkms.v1.ListJobsResponse\x12B\n" +
	"\bWatchJob\x12\x19.dpkms.v1.WatchJobRequest\x1a\x19.dpkms.v1.JobStatusUpdate0\x012\xb3\x02\n" +
	"\fQueryService\x12;\n" +
	"\x06Search\x12\x17.dpkms.v1.SearchRequest\x1a\x18.dpkms.v1.SearchResponse\x12J\n" +
	"\vListObjects\x12\x1c.dpkms.v1.ListObjectsRequest\x1a\x1d.dpkms.v1.ListObjectsResponse\x12B\n" +
	"\tGetObject\x12\x1a.dpkms.v1.GetObjectRequest\x1a\x19.dpkms.v1.KnowledgeObject\x12V\n" +
	"\x0fNodeAwareSearch\x12 .dpkms.v1.NodeAwareSearchRequest\x1a!.dpkms.v1.NodeAwareSearchResponse2\xfa\x01\n" +
	"\rEntityService\x12M\n" +
	"\fListEntities\x12\x1d.dpkms.v1.ListEntitiesRequest\x1a\x1e.dpkms.v1.ListEntitiesResponse\x129\n" +
	"\tGetEntity\x12\x1a.dpkms.v1.GetEntityRequest\x1a\x10.dpkms.v1.Entity\x12_\n" +
	"\x12GetEntityBacklinks\x12#.dpkms.v1.GetEntityBacklinksRequest\x1a$.dpkms.v1.GetEntityBacklinksResponseB:Z8github.com/ideacrafterslabs/ctxt/internal/server/grpc/pbb\x06proto3"

var (
	file_dpkms_proto_rawDescOnce sync.Once
	file_dpkms_proto_rawDescData []byte
)

func file_dpkms_proto_rawDescGZIP() []byte {
	file_dpkms_proto_rawDescOnce.Do(func() {
		file_dpkms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dpkms_proto_rawDesc), len(file_dpkms_proto_rawDesc)))
	})
	return file_dpkms_proto_rawDescData
}

var file_dpkms_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_dpkms_proto_goTypes = []any{
	(*GraphNode)(nil),                  // 0: dpkms.v1.GraphNode
	(*GraphEdge)(nil),                  // 1: dpkms.v1.GraphEdge
	(*ObjectGraph)(nil),                // 2: dpkms.v1.ObjectGraph
	(*Section)(nil),                    // 3: dpkms.v1.Section
	(*DocumentProjection)(nil),         // 4: dpkms.v1.DocumentProjection
	(*KnowledgeObject)(nil),            // 5: dpkms.v1.KnowledgeObject
	(*Entity)(nil),                     // 6: dpkms.v1.Entity
	(*Job)(nil),                        // 7: dpkms.v1.Job
	(*NodeHit)(nil),                    // 8: dpkms.v1.NodeHit
	(*NodeAwareFilter)(nil),            // 9: dpkms.v1.NodeAwareFilter
	(*NodeAwareResult)(nil),            // 10: dpkms.v1.NodeAwareResult
	(*AnalyzeRequest)(nil),             // 11: dpkms.v1.AnalyzeRequest
	(*AnalyzeResponse)(nil),            // 12: dpkms.v1.AnalyzeResponse
	(*GetJobRequest)(nil),              // 13: dpkms.v1.GetJobRequest
	(*ListJobsRequest)(nil),            // 14: dpkms.v1.ListJobsRequest
	(*ListJobsResponse)(nil),           // 15: dpkms.v1.ListJobsResponse
	(*WatchJobRequest)(nil),            // 16: dpkms.v1.WatchJobRequest
	(*JobStatusUpdate)(nil),            // 17: dpkms.v1.JobStatusUpdate
	(*SearchRequest)(nil),              // 18: dpkms.v1.SearchRequest
	(*SearchResponse)(nil),             // 19: dpkms.v1.SearchResponse
	(*ListObjectsRequest)(nil),         // 20: dpkms.v1.ListObjectsRequest
	(*ListObjectsResponse)(nil),        // 21: dpkms.v1.ListObjectsResponse
	(*GetObjectRequest)(nil),           // 22: dpkms.v1.GetObjectRequest
	(*NodeAwareSearchRequest)(nil),     // 23: dpkms.v1.NodeAwareSearchRequest
	(*NodeAwareSearchResponse)(nil),    // 24: dpkms.v1.NodeAwareSearchResponse
	(*ListEntitiesRequest)(nil),        // 25: dpkms.v1.ListEntitiesRequest
	(*ListEntitiesResponse)(nil),       // 26: dpkms.v1.ListEntitiesResponse
	(*GetEntityRequest)(nil),           // 27: dpkms.v1.GetEntityRequest
	(*GetEntityBacklinksRequest)(nil),  // 28: dpkms.v1.GetEntityBacklinksRequest
	(*GetEntityBacklinksResponse)(nil), // 29: dpkms.v1.GetEntityBacklinksResponse
	(*timestamppb.Timestamp)(nil),      // 30: google.protobuf.Timestamp
}
var file_dpkms_proto_depIdxs = []int32{
	0,  // 0: dpkms.v1.ObjectGraph.nodes:type_name -> dpkms.v1.GraphNode
	1,  // 1: dpkms.v1.ObjectGraph.edges:type_name -> dpkms.v1.GraphEdge
	3,  // 2: dpkms.v1.DocumentProjection.sections:type_name -> dpkms.v1.Section
	30, // 3: dpkms.v1.KnowledgeObject.created_at:type_name -> google.protobuf.Timestamp
	30, // 4: dpkms.v1.KnowledgeObject.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: dpkms.v1.KnowledgeObject.graph:type_name -> dpkms.v1.ObjectGraph
	4,  // 6: dpkms.v1.KnowledgeObject.document_view:type_name -> dpkms.v1.DocumentProjection
	30, // 7: dpkms.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	30, // 8: dpkms.v1.Job.updated_at:type_name -> google.protobuf.Timestamp
	30, // 9: dpkms.v1.Job.started_at:type_name -> google.protobuf.Timestamp
	30, // 10: dpkms.v1.Job.completed_at:type_name -> google.protobuf.Timestamp
	5,  // 11: dpkms.v1.NodeAwareResult.object:type_name -> dpkms.v1.KnowledgeObject
	8,  // 12: dpkms.v1.NodeAwareResult.node_hits:type_name -> dpkms.v1.NodeHit
	4,  // 13: dpkms.v1.NodeAwareResult.document_view:type_name -> dpkms.v1.DocumentProjection
	7,  // 14: dpkms.v1.ListJobsResponse.jobs:type_name -> dpkms.v1.Job
	30, // 15: dpkms.v1.JobStatusUpdate.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 16: dpkms.v1.SearchResponse.objects:type_name -> dpkms.v1.KnowledgeObject
	5,  // 17: dpkms.v1.ListObjectsResponse.objects:type_name -> dpkms.v1.KnowledgeObject
	9,  // 18: dpkms.v1.NodeAwareSearchRequest.filter:type_name -> dpkms.v1.NodeAwareFilter
	10, // 19: dpkms.v1.NodeAwareSearchResponse.results:type_name -> dpkms.v1.NodeAwareResult
	6,  // 20: dpkms.v1.ListEntitiesResponse.entities:type_name -> dpkms.v1.Entity
	5,  // 21: dpkms.v1.GetEntityBacklinksResponse.objects:type_name -> dpkms.v1.KnowledgeObject
	11, // 22: dpkms.v1.AnalyzeService.Analyze:input_type -> dpkms.v1.AnalyzeRequest
	13, // 23: dpkms.v1.JobService.GetJob:input_type -> dpkms.v1.GetJobRequest
	14, // 24: dpkms.v1.JobService.ListJobs:input_type -> dpkms.v1.ListJobsRequest
	16, // 25: dpkms.v1.JobService.WatchJob:input_type -> dpkms.v1.WatchJobRequest
	18, // 26: dpkms.v1.QueryService.Search:input_type -> dpkms.v1.SearchRequest
	20, // 27: dpkms.v1.QueryService.ListObjects:input_type -> dpkms.v1.ListObjectsRequest
	22, // 28: dpkms.v1.QueryService.GetObject:input_type -> dpkms.v1.GetObjectRequest
	23, // 29: dpkms.v1.QueryService.NodeAwareSearch:input_type -> dpkms.v1.NodeAwareSearchRequest
	25, // 30: dpkms.v1.EntityService.ListEntities:input_type -> dpkms.v1.ListEntitiesRequest
	27, // 31: dpkms.v1.EntityService.GetEntity:input_type -> dpkms.v1.GetEntityRequest
	28, // 32: dpkms.v1.EntityService.GetEntityBacklinks:input_type -> dpkms.v1.GetEntityBacklinksRequest
	12, // 33: dpkms.v1.AnalyzeService.Analyze:output_type -> dpkms.v1.AnalyzeResponse
	7,  // 34: dpkms.v1.JobService.GetJob:output_type -> dpkms.v1.Job
	15, // 35: dpkms.v1.JobService.ListJobs:output_type -> dpkms.v1.ListJobsResponse
	17, // 36: dpkms.v1.JobService.WatchJob:output_type -> dpkms.v1.JobStatusUpdate
	19, // 37: dpkms.v1.QueryService.Search:output_type -> dpkms.v1.SearchResponse
	21, // 38: dpkms.v1.QueryService.ListObjects:output_type -> dpkms.v1.ListObjectsResponse
	5,  // 39: dpkms.v1.QueryService.GetObject:output_type -> dpkms.v1.KnowledgeObject
	24, // 40: dpkms.v1.QueryService.NodeAwareSearch:output_type -> dpkms.v1.NodeAwareSearchResponse
	26, // 41: dpkms.v1.EntityService.ListEntities:output_type -> dpkms.v1.ListEntitiesResponse
	6,  // 42: dpkms.v1.EntityService.GetEntity:output_type -> dpkms.v1.Entity
	29, // 43: dpkms.v1.EntityService.GetEntityBacklinks:output_type -> dpkms.v1.GetEntityBacklinksResponse
	33, // [33:44] is the sub-list for method output_type
	22, // [22:33] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_dpkms_proto_init() }
func file_dpkms_proto_init() {
	if File_dpkms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dpkms_proto_rawDesc), len(file_dpkms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_dpkms_proto_goTypes,
		DependencyIndexes: file_dpkms_proto_depIdxs,
		MessageInfos:      file_dpkms_proto_msgTypes,
	}.Build()
	File_dpkms_proto = out.File
	file_dpkms_proto_goTypes = nil
	file_dpkms_proto_depIdxs = nil
}
