version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ctxt
    main: ./cmd/ctxt
    binary: ctxt
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  - id: dpkms
    main: ./cmd/dpkms
    binary: dpkms
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: ctxt-archive
    builds: [ctxt]
    name_template: "ctxt_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

  - id: dpkms-archive
    builds: [dpkms]
    name_template: "dpkms_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Dependencies
      regexp: '^.*?(dep|deps|dependencies)(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  footer: |
    **Full Changelog**: https://github.com/ideacrafterslabs/ctxt/compare/{{ .PreviousTag }}...{{ .Tag }}
