package cmd

import (
	"fmt"
	"strings"
	"time"

	"github.com/ideacrafterslabs/ctxt/internal/cli/cliconv"
	discordimporter "github.com/ideacrafterslabs/ctxt/internal/importer/discord"
	"github.com/spf13/cobra"
)

var importDiscordCmd = &cobra.Command{
	Use:   "discord",
	Short: "Import messages from a Discord export file",
	Long: `Import messages from a local DiscordChatExporter JSON export file.

The expected input is a JSON export file generated by DiscordChatExporter
(https://github.com/Tyrrrz/DiscordChatExporter), which produces a single
JSON file per channel with this top-level structure:

  {
    "guild": { "id": "...", "name": "..." },
    "channel": { "id": "...", "name": "..." },
    "messages": [...]
  }

Required from user:
  1) --file path to the Discord JSON export file

Selective import scope:
  --since RFC3339 or YYYY-MM-DD     only import messages on or after this time
  --max-items N                     cap selected messages

Examples:
  # Dry-run and preview messages
  ctxt import discord --file ./export.json --dry-run

  # Import only recent messages
  ctxt import discord --file ./export.json --since 2026-01-01

  # Import with a server override
  ctxt import discord --file ./export.json --server http://localhost:8080`,
	RunE: runImportDiscord,
}

func init() {
	importCmd.AddCommand(importDiscordCmd)

	importDiscordCmd.Flags().String("file", "", "path to Discord JSON export file")
	importDiscordCmd.Flags().String("since", "", "only import messages on or after this time (RFC3339 or YYYY-MM-DD)")
	importDiscordCmd.Flags().Int("max-items", 0, "maximum messages to import (0 = all)")
	importDiscordCmd.Flags().String("server", "", "dpkms server URL (default http://localhost:8080)")
	importDiscordCmd.Flags().String("pipeline", "", "pipeline override for enqueued jobs")

	importDiscordCmd.MarkFlagRequired("file")

	cliconv.WithSideEffect(importDiscordCmd, cliconv.SideEffectWrite)
	cliconv.WithIdempotency(importDiscordCmd, cliconv.IdempotencyConditional)

	cliconv.WithExamples(importDiscordCmd, []cliconv.Example{
		{
			Title:   "Import from default source",
			Command: "ctxt import discord --file ./export.json",
		},
		{
			Title:   "Dry-run preview",
			Command: "ctxt import discord --file ./export.json --confirm=no --dry-run",
		},
	})
	cliconv.WithNextSteps(importDiscordCmd, []cliconv.NextStep{
		{When: "on success", Suggest: "ctxt list", Reason: "verify imported items"},
		{When: "on success", Suggest: "ctxt find <keyword>", Reason: "search the newly-imported data"},
	})
}

func runImportDiscord(cmd *cobra.Command, args []string) error {
	file, _ := cmd.Flags().GetString("file")
	sinceRaw, _ := cmd.Flags().GetString("since")
	maxItems, _ := cmd.Flags().GetInt("max-items")
	serverURL, _ := cmd.Flags().GetString("server")
	pipelineName, _ := cmd.Flags().GetString("pipeline")
	dryRun, _ := cmd.Flags().GetBool("dry-run")

	if serverURL == "" {
		serverURL = "http://localhost:8080"
	}
	serverURL = strings.TrimRight(serverURL, "/")

	since, err := parseSinceValue(sinceRaw)
	if err != nil {
		return err
	}

	msgs, err := discordimporter.ParseExportFile(file)
	if err != nil {
		return err
	}
	if len(msgs) == 0 {
		return fmt.Errorf("no discord messages found in %s", file)
	}

	scanned := len(msgs)
	skipped := 0
	selected := make([]discordimporter.Message, 0, len(msgs))

	for _, m := range msgs {
		if since != nil && m.Timestamp.Before(*since) {
			skipped++
			continue
		}
		selected = append(selected, m)
	}

	if maxItems > 0 && len(selected) > maxItems {
		skipped += len(selected) - maxItems
		selected = selected[:maxItems]
	}

	if len(selected) == 0 {
		return fmt.Errorf("no discord messages matched the selected scope")
	}

	if dryRun {
		const previewLimit = 20
		fmt.Printf("Discord messages selected: %d (dry-run)\n", len(selected))
		fmt.Printf("Scanned: %d, Skipped: %d\n", scanned, skipped)

		preview := len(selected)
		if preview > previewLimit {
			preview = previewLimit
		}
		for i := 0; i < preview; i++ {
			m := selected[i]
			botLabel := ""
			if m.AuthorIsBot {
				botLabel = " [bot]"
			}
			fmt.Printf("%d. [#%s] %s%s (%s): %s\n",
				i+1, m.ChannelName, m.AuthorName, botLabel,
				m.Timestamp.UTC().Format(time.RFC3339),
				truncateText(m.Content, 60))
		}
		if len(selected) > previewLimit {
			fmt.Printf("... and %d more messages\n", len(selected)-previewLimit)
		}
		return nil
	}

	var (
		success  int
		failed   int
		firstErr error
	)

	for _, m := range selected {
		content := discordimporter.RenderContent(m)
		source := m.Source
		if source == "" {
			source = "import:discord"
		}

		_, err := enqueueContent(serverURL, content, "text", pipelineName, source)
		if err != nil {
			failed++
			if firstErr == nil {
				firstErr = err
			}
			continue
		}
		success++
	}

	fmt.Printf("Discord messages processed: %d\n", len(selected))
	fmt.Printf("Scanned: %d, Skipped: %d\n", scanned, skipped)
	fmt.Printf("Jobs enqueued: %d\n", success)
	if failed > 0 {
		fmt.Printf("Jobs failed: %d\n", failed)
	}

	if firstErr != nil {
		return fmt.Errorf("failed to enqueue %d discord messages (first error: %w)", failed, firstErr)
	}

	return nil
}
