/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObjectsIndexRouteImport } from './routes/objects/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ObjectsIdRouteImport } from './routes/objects/$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdRoute = ObjectsIdRouteImport.update({
  id: '/objects/$id',
  path: '/objects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/search': typeof SearchRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/objects/': typeof ObjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/search': typeof SearchRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/jobs': typeof JobsIndexRoute
  '/objects': typeof ObjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/search': typeof SearchRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/objects/': typeof ObjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registry'
    | '/search'
    | '/objects/$id'
    | '/jobs/'
    | '/objects/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/registry' | '/search' | '/objects/$id' | '/jobs' | '/objects'
  id:
    | '__root__'
    | '/'
    | '/registry'
    | '/search'
    | '/objects/$id'
    | '/jobs/'
    | '/objects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistryRoute: typeof RegistryRoute
  SearchRoute: typeof SearchRoute
  ObjectsIdRoute: typeof ObjectsIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id': {
      id: '/objects/$id'
      path: '/objects/$id'
      fullPath: '/objects/$id'
      preLoaderRoute: typeof ObjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistryRoute: RegistryRoute,
  SearchRoute: SearchRoute,
  ObjectsIdRoute: ObjectsIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
